# Default environment variables
# https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables

# How to set env variables
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsenv

# Generate personal access token
# https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line

name: Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [15.X]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm i yarn -g
          yarn -v
          yarn
          yarn export

      - name: Deployment
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
        run: |
          REMOTE_ORIGIN=https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}
          touch out/.nojekyll
          echo kit.set.sh >> out/CNAME
          cd out
          git init
          git config user.name ${GITHUB_ACTOR}
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add . -f
          git commit -m "deploy: from Github action - $(date +"%T")"
          git push --force ${REMOTE_ORIGIN} master:${TARGET_BRANCH}
